### ISSUE TITLE
the main file or the follow up of running the code

### ISSUE THREAD

**Issue by Yousef-Alhattab** [zenerselom/maritime_safety_security#1]
hey there,

I have been going through your code, but the thing I did not get is the follow up of the code. I mean why would not you provide the main file of combining the code? could it be possible for you to help me out with that, please?

**Comment by zenerselom** [comment]
hey there, sorry for the late answer:
if you have read the readme file, you will notice that, this is a tool to include in your own program.
ship_detection.py is the main to use to implement detection.

**Comment by Yousef-Alhattab** [comment]
thanks a lot

I have a question please  in the second section (Custom trained YOLOV3 model on our dataset with pytorch For this purpose colab jupyter notebook was used: )  

you made this line in colab:

!python trainw.py --epochs 150 --batch_size 16 --weights_path "config/1-20.weights" --image_folder "data/seaship/images" --model_config_path "config/yolov31.cfg" --data_config_path "config/seasship.data" --class_path "config/seasship.names" --checkpoint_interval 3 --checkpoint_dir '/content/gdrive/MyDrive/Seasships'


is 1-20.weight here the weight of yolov3 itself?? or I shouldn't include it in the training??


would it be possible to give an explanation please

**Comment by zenerselom** [comment]
1.20.weight was my own checkpoint i saved.
You don't have to use that for your own training.
