### ISSUE TITLE
cant find these files seasship.data, seasship.names, yolov31.cfg, 1-20.weights, train.py  and trainw.py

### ISSUE THREAD

**Issue by Yousef-Alhattab** [zenerselom/maritime_safety_security#2]
Hey there
could you provide these file please files 
seasship.data,
seasship.names, 
yolov31.cfg,
 1-20.weights, 
train.py  
and
trainw.py

**Comment by zenerselom** [comment]
hey there, sorry for the late answer:
1-20.weights is to heavy to put here. that is why i provide necessary infos to train on your own
i will upload  : seasship.data, seasship.names, yolov31.cfg, train.py and trainw.py
find a link to download 1-20.weight : https://drive.google.com/file/d/1--MoxIu-Qx20zJgTeH7E51wztaloK3xv/view?usp=sharing
